name: Python Package Install and S3 Push

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9

            - name: Install dependencies
              run: |
                  pip install sphinx
                  pip install furo
                  pip install sphinx_tabs
                  pip install sphinx_togglebutton

            - name: Run shell command
              run: |
                  echo "Running shell command"
                  sphinx-build -M html source build

            # - name: Configure AWS credentials
            #   uses: aws-actions/configure-aws-credentials@v1
            #   with:
            #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            #       aws-region: us-east-1

            # - name: Push files to S3
            #   run: |
            #       aws s3 sync . s3://your-bucket-name
